apollo: gcc-7 requires include <functional> for std::function
Fixes compile error:
...
./cyber/data/cache_buffer.h:33:31: error: 'function' in namespace 'std' does not name a template type
   using FusionCallback = std::function<void(const T&)>;
...

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>