apollo-common: add missing link option -Wl,-lfastrtps -Wl,-lfastcdr
Here is a link failure
...
undefined reference to `vtable for eprosima::fastrtps::PresentationQosPolicy'
...

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>