fix build error while gcc > 7.1
...
./cyber/class_loader/class_loader.h:91:26: error: 'bind' is not a member of 'std'
   91 |       class_object, std::bind(&ClassLoader::OnClassObjDeleter<Base>, this,
      |                          ^~~~
./cyber/class_loader/class_loader.h:26:1: note: 'std::bind' is defined in header '<functional>'; did you forget to '#include <functional>'?
   25 | #include "cyber/class_loader/class_loader_register_macro.h"
  +++ |+#include <functional>
...

Add a missing functional include to fix the issue

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>